---
- name: Ensure requiered Uptime Kuma dependency is present.
  ansible.builtin.apt:
    name:
      - chromium
      - git
    state: present

- name: Create new user uptime-kuma for launch the application.
  ansible.builtin.user:
    name: uptime-kuma
    home: /var/lib/uptime-kuma
    create_home: true
    system: true

- name: Clone Uptime Kuma github repository.
  ansible.builtin.git:
    repo: "{{ app_repository_url }}"
    dest: "{{ app_repository_dir }}"
    version: "{{ app_version }}"
  register: app_updated
  notify: Restart uptime-kuma

- name: Mark Uptime Kuma repository as safe.
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ app_repository_dir }}"

- name: Set ownership to uptime-kuma user.
  ansible.builtin.file:
    path: "{{ app_repository_dir }}"
    owner: uptime-kuma
    recurse: true
  when: app_updated.changed

- name: Install Uptime Kuma dependencies.
  ansible.builtin.command:
    cmd: npm ci --omit dev
    chdir: "{{ app_repository_dir }}"
  become: true
  become_user: uptime-kuma
  changed_when: app_updated.changed
  when: app_updated.changed

- name: Download Uptime Kuma distribution.
  ansible.builtin.command:
    cmd: npm run download-dist
    chdir: "{{ app_repository_dir }}"
  become: true
  become_user: uptime-kuma
  changed_when: app_updated.changed
  when: app_updated.changed

- name: Create Chromium symlink.
  ansible.builtin.file:
    src: /usr/bin/chromium
    dest: "{{ app_repository_dir }}/chromium"
    state: link

- name: Copy systemd configuration template in place.
  ansible.builtin.template:
    src: "{{ systemd_template }}"
    dest: "/etc/systemd/system/uptime-kuma.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart uptime-kuma

- name: Ensure uptime-kuma is running and enabled on boot.
  ansible.builtin.systemd_service:
    name: uptime-kuma
    state: started
    enabled: true
