---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 3"

defaults:
  run:
    working-directory: 'uptime-kuma'

jobs:

  lint:
    name: Lint
    runs-on: debian-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'uptime-kuma'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: debian-latest
    strategy:
      matrix:
        include:
          - distro: debian13
            playbook: converge.yml
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'uptime-kuma'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Can't go to 3.14+ until Ansible 13.x

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
